import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Loader } from '@/components/Loader'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export interface Props {
  data: Dataprops[];
}

export interface Dataprops {
  id: string,
  name: string,
  tag: string,
  color: string,
  criteria: criteria[]
}

interface criteria {
  text: string,
  type: string
}

export default function Home() {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [postsData, setPostsData] = useState<Dataprops[]>();
  const fetchData = async () => {
    setLoading(true)
    await axios.get('https://jsonware.com/api/v1/json/402b9d6d-9862-4c19-b336-c456999258d6')
      .then((res) => {
        setPostsData(res.data.data)
        setLoading(false)
      }).catch((e) => {
        setError(e)
        setLoading(false)
      })
  }

  useEffect(() => {
    fetchData()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100'>
        <div className='h-screen w-full flex justify-center items-center'>

          {
            error === null && loading ? <Loader /> :
              error !== null ? <p>{error}</p> :
                postsData &&
                <div className='bg-white rounded-md'>
                  {postsData.map((post: Dataprops) => {
                    return (
                      <Link key={post.id} href={`details/${post.id}`}>
                        <div className='hover:bg-gray-50 px-5 py-4 flex justify-between border-b'>
                          <h1 className='text-indigo-600 font-medium flex-1'>{post.name}</h1>
                          <div className={` text-xs ml-16 inline-flex items-center font-bold leading-sm px-3 py-1 rounded-full $
                          bg-${post.color.toString()}-100 text-${post.color.toString()}-700
                          `}>
                            {post.tag}
                          </div>
                          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5 text-gray-500 ml-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                          </svg>
                        </div>
                      </Link>
                    )
                  })}
                </div>
          }
        </div>
      </main>
    </>
  )
}
